'use server';

/**
 * @fileOverview A Genkit flow for generating personalized schedule plans for students.
 *
 * - generateSchedulePlan - A function that generates a personalized schedule plan.
 * - SchedulePlanInput - The input type for the generateSchedulePlan function.
 * - SchedulePlanOutput - The return type for the generateSchedulePlan function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';
import academicConfig from '@/lib/academic_config.json';

const PersonalTaskSchema = z.object({
  name: z.string().describe('The name of the personal task or study goal.'),
  duration: z.number().describe('The duration of the task in hours.'),
  priority: z.enum(['Low', 'Medium', 'High']).describe('The priority of the task.'),
  preferredDays: z.array(z.string()).optional().describe('Optional preferred days for the task (e.g., ["Monday", "Wednesday"]).'),
});

const SchedulePlanInputSchema = z.object({
  studentId: z.string().describe('The ID of the student.'),
  instituteTimetable: z.string().describe('The student\'s fixed weekly institute timetable in a structured format (e.g., JSON string). This is non-negotiable.'),
  personalTasks: z.array(PersonalTaskSchema).describe('An array of personal tasks and study goals to be scheduled.'),
});
export type SchedulePlanInput = z.infer<typeof SchedulePlanInputSchema>;


const ScheduledTaskSchema = z.object({
  taskName: z.string(),
  day: z.string(),
  time: z.string(),
  isClass: z.boolean(),
});

const SchedulePlanOutputSchema = z.object({
  schedule: z.record(z.array(ScheduledTaskSchema)).describe('The generated schedule plan, with days of the week as keys. Each day has an array of scheduled tasks or classes.'),
  reasoning: z.string().describe('An explanation of how the schedule was constructed, including how priorities were handled and why any tasks could not be scheduled.'),
});
export type SchedulePlanOutput = z.infer<typeof SchedulePlanOutputSchema>;

export async function generateSchedulePlan(input: SchedulePlanInput): Promise<SchedulePlanOutput> {
  return generateSchedulePlanFlow(input);
}

const schedulePrompt = ai.definePrompt({
    name: 'aiSchedulePlannerPrompt',
    input: { schema: z.object({
        instituteTimetable: z.string(),
        personalTasks: z.string(),
    })},
    output: { schema: SchedulePlanOutputSchema },
    prompt: `You are an academic scheduling AI.
Input includes:
1. Fixed institute class timetable: {{{instituteTimetable}}}
2. Student personal tasks with duration and priority: {{{personalTasks}}}

Rules:
- Do not overlap tasks with classes.
- High priority tasks must be scheduled first.
- Tasks can be split across days if needed, but contiguous blocks are preferred.
- Max 6 study hours per day.
- Output ONLY valid JSON.

Output format:
{
  "schedule": {
    "Monday": [{"time":"","taskName":"","isClass":false, "day":"Monday"}],
    "Tuesday": [],
    "Wednesday": [],
    "Thursday": [],
    "Friday": [],
    "Saturday": []
  },
  "reasoning": "A summary of how the schedule was generated and which tasks could not be fit."
}

Return the best possible schedule even if constraints are tight. Your reasoning should explain your choices.
`
});


// New implementation with Gemini and a deterministic fallback.
const generateSchedulePlanFlow = ai.defineFlow(
  {
    name: 'generateSchedulePlanFlow',
    inputSchema: SchedulePlanInputSchema,
    outputSchema: SchedulePlanOutputSchema,
  },
  async (input) => {
    try {
        const promptInput = {
            instituteTimetable: input.instituteTimetable,
            personalTasks: JSON.stringify(input.personalTasks, null, 2),
        };

        const llmResponse = await schedulePrompt(promptInput);
        const output = llmResponse.output();

        if (!output || !output.schedule) {
            throw new Error("Gemini returned empty or invalid schedule.");
        }
        
        output.reasoning = "[Generated by Gemini AI]\n" + output.reasoning;
        return output;

    } catch (e: any) {
        console.warn("Gemini scheduler failed, using fallback. Error:", e.message);
        
        // --- Fallback to deterministic scheduler ---
        const instituteTimetable = JSON.parse(input.instituteTimetable);
        const personalTasks = input.personalTasks;
        
        const dayMap: { [key: string]: string } = {
            MON: "Monday", TUE: "Tuesday", WED: "Wednesday",
            THU: "Thursday", FRI: "Friday", SAT: "Saturday"
        };
        const weekDays = academicConfig.workingDays.map(d => dayMap[d]).filter(Boolean);
        const timeSlots = academicConfig.timeSlots.map(slot => `${slot.start}-${slot.end}`);
        
        const schedule: SchedulePlanOutput['schedule'] = JSON.parse(JSON.stringify(instituteTimetable));
        weekDays.forEach(day => {
            if (!schedule[day]) {
                schedule[day] = [];
            }
        });

        const isSlotOccupied = (day: string, time: string): boolean => {
            return schedule[day]?.some(task => task.time === time) ?? false;
        };

        const priorityOrder = { 'High': 1, 'Medium': 2, 'Low': 3 };
        const sortedTasks = [...personalTasks].sort((a, b) => priorityOrder[a.priority] - priorityOrder[b.priority]);

        const unscheduledTasks: string[] = [];
        const scheduledTasks: string[] = [];
        
        for (const task of sortedTasks) {
            let isTaskScheduled = false;
            const taskDuration = Math.ceil(task.duration);

            for (const day of weekDays) {
                if (isTaskScheduled) break;
                for (let i = 0; i <= timeSlots.length - taskDuration; i++) {
                    const potentialSlots = timeSlots.slice(i, i + taskDuration);
                    const isBlockFree = potentialSlots.every(slot => !isSlotOccupied(day, slot));
                    
                    let isContinuous = true;
                    for (let j = 0; j < potentialSlots.length - 1; j++) {
                        const currentSlotEnd = potentialSlots[j].split('-')[1];
                        const nextSlotStart = potentialSlots[j+1].split('-')[0];
                        if (currentSlotEnd !== nextSlotStart) {
                            isContinuous = false;
                            break;
                        }
                    }
                    
                    if (isBlockFree && isContinuous) {
                        for (const slot of potentialSlots) {
                            schedule[day].push({
                                taskName: task.name,
                                time: slot,
                                isClass: false,
                                day: day,
                            });
                        }
                        scheduledTasks.push(`'${task.name}' (${task.duration}h, ${task.priority} priority)`);
                        isTaskScheduled = true;
                        break; 
                    }
                }
            }
            if (!isTaskScheduled) {
                unscheduledTasks.push(`'${task.name}' (${task.duration}h)`);
            }
        }

        for (const day in schedule) {
            schedule[day].sort((a, b) => a.time.localeCompare(b.time));
        }

        let reasoning = "[Fallback Scheduler Used]\nGemini AI could not generate a plan, so a basic scheduler was used.\n\n";
        reasoning += "1. Your institute classes were treated as fixed appointments.\n";
        reasoning += "2. Your personal tasks were sorted by priority (High > Medium > Low).\n";
        reasoning += "3. The scheduler then found the first available free time blocks.\n\n";

        if (scheduledTasks.length > 0) {
            reasoning += `Successfully scheduled: ${scheduledTasks.join(', ')}.\n`;
        }
        if (unscheduledTasks.length > 0) {
            reasoning += `\nCould not schedule: ${unscheduledTasks.join(', ')} due to lack of contiguous free time.`;
        } else if (personalTasks.length > 0) {
            reasoning += "\nAll tasks were successfully scheduled!";
        } else {
             reasoning += "No personal tasks were provided.";
        }
        
        return { schedule, reasoning };
    }
  }
);
