import { PlaceHolderImages } from "./placeholder-images";

export const dummySchedule = [
    { time: "09:00 - 10:00", subject: "Data Structures", venue: "C-201" },
    { time: "10:00 - 11:00", subject: "Algorithms", venue: "C-202" },
    { time: "11:15 - 12:15", subject: "Database Systems", venue: "Lab 3" },
    { time: "14:00 - 15:00", subject: "Operating Systems", venue: "C-105" },
];

export const dummyAnnouncements = [
    {
        title: "HackOverflow 2024 Registrations Open",
        category: "Hackathons",
        date: "July 20, 2024",
        image: PlaceHolderImages.find(img => img.id === 'announcement-1')!
    },
    {
        title: "Guest Lecture on Quantum Computing",
        category: "Events",
        date: "July 22, 2024",
        image: PlaceHolderImages.find(img => img.id === 'announcement-2')!
    },
    {
        title: "Robotics Club Recruitment Drive",
        category: "Clubs",
        date: "July 25, 2024",
        image: PlaceHolderImages.find(img => img.id === 'announcement-3')!
    },
];

export const dummyCourses = [
  { id: 'DSA1', name: 'Data Structures & Algorithms I' },
  { id: 'DSA4', name: 'Data Structures & Algorithms IV' },
  { id: 'SS2', name: 'Soft Skills II' },
  { id: 'OPC3', name: 'Open Elective III' },
  { id: 'PS3', name: 'Problem Solving III' },
  { id: 'CA4', name: 'Computer Architecture IV' },
  { id: 'BEC', name: 'Basic Electronics' },
  { id: 'CA2', name: 'Computer Architecture II' },
  { id: 'PS1', name: 'Problem Solving I' },
  { id: 'SS3', name: 'Soft Skills III' },
  { id: 'CA1', name: 'Computer Architecture I' },
  { id: 'SS1', name: 'Soft Skills I' },
  { id: 'PS2', name: 'Problem Solving II' },
  { id: 'PS4', name: 'Problem Solving IV' },
  { id: 'PS5', name: 'Problem Solving V' },
  { id: 'OPC2', name: 'Open Elective II' },
  { id: 'DSA3', name: 'Data Structures & Algorithms III' },
  { id: 'SS4', name: 'Soft Skills IV' },
  { id: 'DSA2', name: 'Data Structures & Algorithms II' },
  { id: 'OPC1', name: 'Open Elective I' },
  { id: 'OPC4', name: 'Open Elective IV' },
  { id: 'AIV2', name: 'AI & Vulnerabilities II' },
  { id: 'AIV1', name: 'AI & Vulnerabilities I' },
  { id: 'EDL1', name: 'Eng. Design & Logic I' },
  { id: 'EDL2', name: 'Eng. Design & Logic II' },
];

export const dummyFaculty = [
    { id: 'faculty-1', name: 'Dr. John Doe', email: 'john.d@iiits.in', courses: ['DSA1', 'DSA2', 'DSA3', 'DSA4'], ugYear: [1], branch: 'CSE', section: 'A' },
    { id: 'faculty-2', name: 'Dr. Jane Smith', email: 'jane.s@iiits.in', courses: ['SS1', 'SS2', 'SS3', 'SS4'], ugYear: [1], branch: 'Common', section: 'Common Class' },
    { id: 'faculty-3', name: 'Dr. Robert Brown', email: 'robert.b@iiits.in', courses: ['PS1', 'PS2', 'PS3', 'PS4', 'PS5'], ugYear: [1], branch: 'CSE', section: 'B' },
    { id: 'faculty-4', name: 'Dr. Emily White', email: 'emily.w@iiits.in', courses: ['CA1', 'CA2', 'CA3', 'CA4'], ugYear: [1], branch: 'CSE', section: 'A' },
    { id: 'faculty-5', name: 'Dr. Michael Green', email: 'michael.g@iiits.in', courses: ['OPC1', 'OPC2', 'OPC3', 'OPC4'], ugYear: [1], branch: 'Common', section: 'Common Class' },
    { id: 'faculty-6', name: 'Dr. Sarah Black', email: 'sarah.b@iiits.in', courses: ['BEC', 'EDL1', 'EDL2'], ugYear: [1], branch: 'ECE', section: 'A' },
    { id: 'faculty-7', name: 'Dr. David Grey', email: 'david.g@iiits.in', courses: ['AIV1', 'AIV2'], ugYear: [1], branch: 'AIDS', section: 'A' },
];

export const dummyTimetable = {
    "UG1": {
        "Common": [
            // Monday
            { day: "Monday", time: "08:45-09:45", course: "DSA1", faculty: "Dr. John Doe", room: "G09" },
            { day: "Monday", time: "08:45-09:45", course: "DSA4", faculty: "Dr. John Doe", room: "G08" },
            { day: "Monday", time: "08:45-09:45", course: "SS2", faculty: "Dr. Jane Smith", room: "Lab 103" },
            { day: "Monday", time: "08:45-09:45", course: "OPC3", faculty: "Dr. Michael Green", room: "G07" },
            { day: "Monday", time: "09:45-10:45", course: "SS2", faculty: "Dr. Jane Smith", room: "Lab 103" },
            { day: "Monday", time: "09:45-10:45", course: "PS3", faculty: "Dr. Robert Brown", room: "G08" },
            { day: "Monday", time: "11:00-12:00", course: "CA2", faculty: "Dr. Emily White", room: "G09" },
            { day: "Monday", time: "11:00-12:00", course: "PS1", faculty: "Dr. Robert Brown", room: "G07" },
            { day: "Monday", time: "11:00-12:00", course: "SS3", faculty: "Dr. Jane Smith", room: "Lab 103" },
            { day: "Monday", time: "12:00-13:00", course: "SS3", faculty: "Dr. Jane Smith", room: "Lab 103" },
            { day: "Monday", time: "12:00-13:00", course: "PS2", faculty: "Dr. Robert Brown", room: "G09" },
            { day: "Monday", time: "12:00-13:00", course: "CA1", faculty: "Dr. Emily White", room: "G08" },
            { day: "Monday", time: "12:00-13:00", course: "BEC", faculty: "Dr. Sarah Black", room: "G07" },
            { day: "Monday", time: "14:15-15:15", course: "SS1", faculty: "Dr. Jane Smith", room: "G08" },
            { day: "Monday", time: "14:15-15:15", course: "DSA2", faculty: "Dr. John Doe", room: "Lab 103" },
            { day: "Monday", time: "14:15-15:15", course: "SS4", faculty: "Dr. Jane Smith", room: "G09" },
            { day: "Monday", time: "15:15-16:15", course: "DSA2", faculty: "Dr. John Doe", room: "Lab 103" },
            { day: "Monday", time: "15:15-16:15", course: "OPC4", faculty: "Dr. Michael Green", room: "G08" },
            { day: "Monday", time: "16:30-17:30", course: "CA4", faculty: "Dr. Emily White", room: "G08" },
            { day: "Monday", time: "16:30-17:30", course: "PS5", faculty: "Dr. Robert Brown", room: "G09" },
            { day: "Monday", time: "16:30-17:30", course: "CA3", faculty: "Dr. Emily White", room: "G07" },
            // Tuesday
            { day: "Tuesday", time: "08:45-09:45", course: "CA4", faculty: "Dr. Emily White", room: "Lab 103" },
            { day: "Tuesday", time: "08:45-09:45", course: "BEC", faculty: "Dr. Sarah Black", room: "Lab 114/102" },
            { day: "Tuesday", time: "09:45-10:45", course: "BEC", faculty: "Dr. Sarah Black", room: "Lab 114/102" },
            { day: "Tuesday", time: "09:45-10:45", course: "CA4", faculty: "Dr. Emily White", room: "Lab 103" },
            { day: "Tuesday", time: "11:00-12:00", course: "CA2", faculty: "Dr. Emily White", room: "Lab 103" },
            { day: "Tuesday", time: "11:00-12:00", course: "DSA1", faculty: "Dr. John Doe", room: "G09" },
            { day: "Tuesday", time: "11:00-12:00", course: "DSA3", faculty: "Dr. John Doe", room: "G08" },
            { day: "Tuesday", time: "12:00-13:00", course: "CA2", faculty: "Dr. Emily White", room: "Lab 103" },
            { day: "Tuesday", time: "12:00-13:00", course: "SS1", faculty: "Dr. Jane Smith", room: "G09" },
            { day: "Tuesday", time: "12:00-13:00", course: "SS3", faculty: "Dr. Jane Smith", room: "G07" },
            { day: "Tuesday", time: "14:15-15:15", course: "PS2", faculty: "Dr. Robert Brown", room: "G09" },
            { day: "Tuesday", time: "14:15-15:15", course: "DSA3", faculty: "Dr. John Doe", room: "Lab 103" },
            { day: "Tuesday", time: "14:15-15:15", course: "OPC1", faculty: "Dr. Michael Green", room: "G08" },
            { day: "Tuesday", time: "15:15-16:15", course: "DSA2", faculty: "Dr. John Doe", room: "G08" },
            { day: "Tuesday", time: "15:15-16:15", course: "DSA3", faculty: "Dr. John Doe", room: "Lab 103" },
            { day: "Tuesday", time: "15:15-16:15", course: "PS1", faculty: "Dr. Robert Brown", room: "G09" },
            { day: "Tuesday", time: "16:30-17:30", course: "SS2", faculty: "Dr. Jane Smith", room: "G09" },
            { day: "Tuesday", time: "16:30-17:30", course: "SS4", faculty: "Dr. Jane Smith", room: "G08" },
            { day: "Tuesday", time: "16:30-17:30", course: "CA1", faculty: "Dr. Emily White", room: "G07" },
            // Wednesday
            { day: "Wednesday", time: "08:45-09:45", course: "DSA1", faculty: "Dr. John Doe", room: "Lab 103" },
            { day: "Wednesday", time: "08:45-09:45", course: "PS2", faculty: "Dr. Robert Brown", room: "G09" },
            { day: "Wednesday", time: "08:45-09:45", course: "PS5", faculty: "Dr. Robert Brown", room: "G08" },
            { day: "Wednesday", time: "08:45-09:45", course: "CA3", faculty: "Dr. Emily White", room: "G07" },
            { day: "Wednesday", time: "09:45-10:45", course: "SS2", faculty: "Dr. Jane Smith", room: "G08" },
            { day: "Wednesday", time: "09:45-10:45", course: "DSA1", faculty: "Dr. John Doe", room: "Lab 103" },
            { day: "Wednesday", time: "11:00-12:00", course: "CA2", faculty: "Dr. Emily White", room: "G08" },
            { day: "Wednesday", time: "11:00-12:00", course: "CA1", faculty: "Dr. Emily White", room: "G07" },
            { day: "Wednesday", time: "11:00-12:00", course: "DSA4", faculty: "Dr. John Doe", room: "Lab 103" },
            { day: "Wednesday", time: "12:00-13:00", course: "DSA4", faculty: "Dr. John Doe", room: "Lab 103" },
            { day: "Wednesday", time: "12:00-13:00", course: "PS4", faculty: "Dr. Robert Brown", room: "G09" },
            { day: "Wednesday", time: "12:00-13:00", course: "PS3", faculty: "Dr. Robert Brown", room: "G08" },
            { day: "Wednesday", time: "14:15-15:15", course: "CA3", faculty: "Dr. Emily White", room: "Lab 103" },
            { day: "Wednesday", time: "14:15-15:15", course: "OPC4", faculty: "Dr. Michael Green", room: "G08" },
            { day: "Wednesday", time: "14:15-15:15", course: "SS1", faculty: "Dr. Jane Smith", room: "G09" },
            { day: "Wednesday", time: "15:15-16:15", course: "DSA2", faculty: "Dr. John Doe", room: "G08" },
            { day: "Wednesday", time: "15:15-16:15", course: "CA3", faculty: "Dr. Emily White", room: "Lab 103" },
            { day: "Wednesday", time: "15:15-16:15", course: "PS1", faculty: "Dr. Robert Brown", room: "G09" },
            { day: "Wednesday", time: "16:30-17:30", course: "Faculty meeting", faculty: "-", room: "-" },
            // Thursday
            { day: "Thursday", time: "08:45-09:45", course: "PS4", faculty: "Dr. Robert Brown", room: "G09" },
            { day: "Thursday", time: "08:45-09:45", course: "PS2", faculty: "Dr. Robert Brown", room: "G08" },
            { day: "Thursday", time: "08:45-09:45", course: "CA3", faculty: "Dr. Emily White", room: "G07" },
            { day: "Thursday", time: "09:45-10:45", course: "DSA4", faculty: "Dr. John Doe", room: "G09" },
            { day: "Thursday", time: "09:45-10:45", course: "DSA1", faculty: "Dr. John Doe", room: "G08" },
            { day: "Thursday", time: "09:45-10:45", course: "SS3", faculty: "Dr. Jane Smith", room: "G07" },
            { day: "Thursday", time: "09:45-10:45", course: "OPC2", faculty: "Dr. Michael Green", room: "G06" },
            { day: "Thursday", time: "11:00-12:00", course: "CA1", faculty: "Dr. Emily White", room: "Lab 103" },
            { day: "Thursday", time: "11:00-12:00", course: "CA2", faculty: "Dr. Emily White", room: "G09" },
            { day: "Thursday", time: "11:00-12:00", course: "CA4", faculty: "Dr. Emily White", room: "G08" },
            { day: "Thursday", time: "12:00-13:00", course: "CA1", faculty: "Dr. Emily White", room: "Lab 103" },
            { day: "Thursday", time: "12:00-13:00", course: "PS3", faculty: "Dr. Robert Brown", room: "G09" },
            { day: "Thursday", time: "12:00-13:00", course: "PS4", faculty: "Dr. Robert Brown", room: "G08" },
            { day: "Thursday", time: "12:00-13:00", course: "SS4", faculty: "Dr. Jane Smith", room: "G05" },
            { day: "Thursday", time: "14:15-15:15", course: "BEC", faculty: "Dr. Sarah Black", room: "G09" },
            { day: "Thursday", time: "14:15-15:15", course: "SS1", faculty: "Dr. Jane Smith", room: "Lab 103" },
            { day: "Thursday", time: "15:15-16:15", course: "SS1", faculty: "Dr. Jane Smith", room: "Lab 103" },
            { day: "Thursday", time: "15:15-16:15", course: "DSA3", faculty: "Dr. John Doe", room: "G08" },
            { day: "Thursday", time: "15:15-16:15", course: "PS5", faculty: "Dr. Robert Brown", room: "G09" },
            { day: "Thursday", time: "16:30-17:30", course: "AIV2", faculty: "Dr. David Grey", room: "G08" },
            { day: "Thursday", time: "17:30-18:30", course: "AIV2", faculty: "Dr. David Grey", room: "G08" },
            // Friday
            { day: "Friday", time: "08:45-09:45", course: "SS3", faculty: "Dr. Jane Smith", room: "G09" },
            { day: "Friday", time: "08:45-09:45", course: "SS2", faculty: "Dr. Jane Smith", room: "G08" },
            { day: "Friday", time: "08:45-09:45", course: "PS5", faculty: "Dr. Robert Brown", room: "G07" },
            { day: "Friday", time: "09:45-10:45", course: "DSA4", faculty: "Dr. John Doe", room: "G09" },
            { day: "Friday", time: "09:45-10:45", course: "CA4", faculty: "Dr. Emily White", room: "G08" },
            { day: "Friday", time: "11:00-12:00", course: "PS3", faculty: "Dr. Robert Brown", room: "G09" },
            { day: "Friday", time: "11:00-12:00", course: "PS4", faculty: "Dr. Robert Brown", room: "G08" },
            { day: "Friday", time: "11:00-12:00", course: "PS1", faculty: "Dr. Robert Brown", room: "G07" },
            { day: "Friday", time: "12:00-13:00", course: "OPC3", faculty: "Dr. Michael Green", room: "G09" },
            { day: "Friday", time: "12:00-13:00", course: "OPC2", faculty: "Dr. Michael Green", room: "B03" },
            { day: "Friday", time: "12:00-13:00", course: "BEC", faculty: "Dr. Sarah Black", room: "G08" },
            { day: "Friday", time: "14:15-15:15", course: "DSA3", faculty: "Dr. John Doe", room: "G09" },
            { day: "Friday", time: "14:15-15:15", course: "DSA2", faculty: "Dr. John Doe", room: "G08" },
            { day: "Friday", time: "14:15-15:15", course: "SS4", faculty: "Dr. Jane Smith", room: "Lab 103" },
            { day: "Friday", time: "15:15-16:15", course: "SS4", faculty: "Dr. Jane Smith", room: "Lab 103" },
            { day: "Friday", time: "15:15-16:15", course: "OPC1", faculty: "Dr. Michael Green", room: "G09" },
            { day: "Friday", time: "16:30-17:30", course: "AIV1", faculty: "Dr. David Grey", room: "G09" },
            { day: "Friday", time: "17:30-18:30", course: "AIV1", faculty: "Dr. David Grey", room: "G09" },
            // Saturday
            { day: "Saturday", time: "08:45-10:45", course: "EDL1", faculty: "Dr. Sarah Black", room: "G09" },
            { day: "Saturday", time: "11:00-13:00", course: "EDL2", faculty: "Dr. Sarah Black", room: "G09" },
        ]
    }
};
