import { PlaceHolderImages } from "./placeholder-images";

export const dummySchedule = [
    { time: "09:00 - 10:00", subject: "Data Structures", venue: "C-201" },
    { time: "10:00 - 11:00", subject: "Algorithms", venue: "C-202" },
    { time: "11:15 - 12:15", subject: "Database Systems", venue: "Lab 3" },
    { time: "14:00 - 15:00", subject: "Operating Systems", venue: "C-105" },
];

export const dummyAnnouncements = [
    {
        title: "HackOverflow 2024 Registrations Open",
        category: "Hackathons",
        date: "July 20, 2024",
        image: PlaceHolderImages.find(img => img.id === 'announcement-1')!
    },
    {
        title: "Guest Lecture on Quantum Computing",
        category: "Events",
        date: "July 22, 2024",
        image: PlaceHolderImages.find(img => img.id === 'announcement-2')!
    },
    {
        title: "Robotics Club Recruitment Drive",
        category: "Clubs",
        date: "July 25, 2024",
        image: PlaceHolderImages.find(img => img.id === 'announcement-3')!
    },
];

export const dummyCourses = [
  { id: 'DSA1', name: 'Data Structures & Algorithms I' },
  { id: 'DSA4', name: 'Data Structures & Algorithms IV' },
  { id: 'SS2', name: 'Soft Skills II' },
  { id: 'OPC3', name: 'Open Elective III' },
  { id: 'PS3', name: 'Problem Solving III' },
  { id: 'CA4', name: 'Computer Architecture IV' },
  { id: 'BEC', name: 'Basic Electronics' },
  { id: 'CA2', name: 'Computer Architecture II' },
  { id: 'PS1', name: 'Problem Solving I' },
  { id: 'SS3', name: 'Soft Skills III' },
  { id: 'CA1', name: 'Computer Architecture I' },
  { id: 'SS1', name: 'Soft Skills I' },
  { id: 'PS2', name: 'Problem Solving II' },
  { id: 'PS4', name: 'Problem Solving IV' },
  { id: 'PS5', name: 'Problem Solving V' },
  { id: 'OPC2', name: 'Open Elective II' },
  { id: 'DSA3', name: 'Data Structures & Algorithms III' },
  { id: 'SS4', name: 'Soft Skills IV' },
  { id: 'DSA2', name: 'Data Structures & Algorithms II' },
  { id: 'OPC1', name: 'Open Elective I' },
  { id: 'OPC4', name: 'Open Elective IV' },
  { id: 'AIV2', name: 'AI & Vulnerabilities II' },
  { id: 'AIV1', name: 'AI & Vulnerabilities I' },
  { id: 'EDL1', name: 'Eng. Design & Logic I' },
  { id: 'EDL2', name: 'Eng. Design & Logic II' },
  { id: 'CA3', name: 'Computer Architecture III' },
];

export const dummyFaculty = [
    { id: 'faculty-1', name: 'Praveen K', email: 'praveen.k@iiits.in', courses: ['DSA1'], ugYear: [1], branch: 'CSE', section: 'A' },
    { id: 'faculty-2', name: 'K V S R', email: 'kvsr@iiits.in', courses: ['DSA4'], ugYear: [1], branch: 'CSE', section: 'A' },
    { id: 'faculty-3', name: 'Satrajit', email: 'satrajit@iiits.in', courses: ['SS2'], ugYear: [1], branch: 'Common', section: 'Common Class' },
    { id: 'faculty-4', name: 'Srinivas B', email: 'srinivas.b@iiits.in', courses: ['OPC3'], ugYear: [1], branch: 'Common', section: 'Common Class' },
    { id: 'faculty-5', name: 'Santhosh C', email: 'santhosh.c@iiits.in', courses: ['PS3'], ugYear: [1], branch: 'CSE', section: 'B' },
    { id: 'faculty-6', name: 'Vandana J', email: 'vandana.j@iiits.in', courses: ['CA2'], ugYear: [1], branch: 'CSE', section: 'A' },
    { id: 'faculty-7', name: 'Bhuvan T', email: 'bhuvan.t@iiits.in', courses: ['PS1'], ugYear: [1], branch: 'CSE', section: 'C' },
    { id: 'faculty-8', name: 'Sujit S', email: 'sujit.s@iiits.in', courses: ['SS3'], ugYear: [1], branch: 'Common', section: 'Common Class' },
    { id: 'faculty-9', name: 'K K B', email: 'kkb@iiits.in', courses: ['PS2'], ugYear: [1], branch: 'CSE', section: 'A' },
    { id: 'faculty-10', name: 'Monalisa G', email: 'monalisa.g@iiits.in', courses: ['CA1'], ugYear: [1], branch: 'CSE', section: 'B' },
    { id: 'faculty-11', name: 'Suneetha K', email: 'suneetha.k@iiits.in', courses: ['BEC'], ugYear: [1], branch: 'ECE', section: 'A' },
    { id: 'faculty-12', name: 'Pankaj V', email: 'pankaj.v@iiits.in', courses: ['SS1'], ugYear: [1], branch: 'Common', section: 'Common Class' },
    { id: 'faculty-13', name: 'Suman Kumar', email: 'suman.k@iiits.in', courses: ['DSA2'], ugYear: [1], branch: 'CSE', section: 'A' },
    { id: 'faculty-14', name: 'Rakesh T', email: 'rakesh.t@iiits.in', courses: ['SS4'], ugYear: [1], branch: 'Common', section: 'Common Class' },
    { id: 'faculty-15', name: 'Kishore K', email: 'kishore.k@iiits.in', courses: ['OPC4'], ugYear: [1], branch: 'Common', section: 'Common Class' },
    { id: 'faculty-16', name: 'Ram K', email: 'ram.k@iiits.in', courses: ['PS5'], ugYear: [1], branch: 'CSE', section: 'C' },
    { id: 'faculty-17', name: 'Prashant K', email: 'prashant.k@iiits.in', courses: ['CA3'], ugYear: [1], branch: 'CSE', section: 'C' },
    { id: 'faculty-18', name: 'Dileep', email: 'dileep@iiits.in', courses: ['CA4'], ugYear: [1], branch: 'CSE', section: 'A' },
    { id: 'faculty-19', name: 'Aakash', email: 'aakash@iiits.in', courses: ['DSA3'], ugYear: [1], branch: 'CSE', section: 'B' },
    { id: 'faculty-20', name: 'Karthik S', email: 'karthik.s@iiits.in', courses: ['OPC1'], ugYear: [1], branch: 'Common', section: 'Common Class' },
    { id: 'faculty-21', name: 'Gautam P', email: 'gautam.p@iiits.in', courses: ['PS4'], ugYear: [1], branch: 'CSE', section: 'B' },
    { id: 'faculty-22', name: 'Anurag S', email: 'anurag.s@iiits.in', courses: ['OPC2'], ugYear: [1], branch: 'Common', section: 'Common Class' },
    { id: 'faculty-23', name: 'Md. Aquib', email: 'md.aquib@iiits.in', courses: ['AIV2'], ugYear: [1], branch: 'AIDS', section: 'A' },
    { id: 'faculty-24', name: 'Mounika J', email: 'mounika.j@iiits.in', courses: ['AIV1'], ugYear: [1], branch: 'AIDS', section: 'A' },
    { id: 'faculty-25', name: 'Srinath', email: 'srinath@iiits.in', courses: ['EDL1'], ugYear: [1], branch: 'ECE', section: 'B' },
    { id: 'faculty-26', name: 'Soumya', email: 'soumya@iiits.in', courses: ['EDL2'], ugYear: [1], branch: 'ECE', section: 'B' },
];

export const dummyTimetable = {
    "UG1": {
        "Common": [
            // Monday
            { day: "Monday", time: "08:45-09:45", course: "DSA1", faculty: "Praveen K", room: "G09" },
            { day: "Monday", time: "08:45-09:45", course: "DSA4", faculty: "K V S R", room: "G08" },
            { day: "Monday", time: "08:45-09:45", course: "SS2", faculty: "Satrajit", room: "Lab 103" },
            { day: "Monday", time: "08:45-09:45", course: "OPC3", faculty: "Srinivas B", room: "G07" },
            { day: "Monday", time: "09:45-10:45", course: "SS2", faculty: "Satrajit", room: "Lab 103" },
            { day: "Monday", time: "09:45-10:45", course: "PS3", faculty: "Santhosh C", room: "G08" },
            { day: "Monday", time: "11:00-12:00", course: "CA2", faculty: "Vandana J", room: "G09" },
            { day: "Monday", time: "11:00-12:00", course: "PS1", faculty: "Bhuvan T", room: "G07" },
            { day: "Monday", time: "11:00-12:00", course: "SS3", faculty: "Sujit S", room: "Lab 103" },
            { day: "Monday", time: "12:00-13:00", course: "SS3", faculty: "Sujit S", room: "Lab 103" },
            { day: "Monday", time: "12:00-13:00", course: "PS2", faculty: "K K B", room: "G09" },
            { day: "Monday", time: "12:00-13:00", course: "CA1", faculty: "Monalisa G", room: "G08" },
            { day: "Monday", time: "12:00-13:00", course: "BEC", faculty: "Suneetha K", room: "G07" },
            { day: "Monday", time: "14:15-15:15", course: "SS1", faculty: "Pankaj V", room: "G08" },
            { day: "Monday", time: "14:15-15:15", course: "DSA2", faculty: "Suman Kumar", room: "Lab 103" },
            { day: "Monday", time: "14:15-15:15", course: "SS4", faculty: "Rakesh T", room: "G09" },
            { day: "Monday", time: "15:15-16:15", course: "DSA2", faculty: "Suman Kumar", room: "Lab 103" },
            { day: "Monday", time: "15:15-16:15", course: "OPC4", faculty: "Kishore K", room: "G08" },
            { day: "Monday", time: "16:30-17:30", course: "CA4", faculty: "Dileep", room: "G08" },
            { day: "Monday", time: "16:30-17:30", course: "PS5", faculty: "Ram K", room: "G09" },
            { day: "Monday", time: "16:30-17:30", course: "CA3", faculty: "Prashant K", room: "G07" },
            // Tuesday
            { day: "Tuesday", time: "08:45-09:45", course: "CA4", faculty: "Dileep", room: "Lab 103" },
            { day: "Tuesday", time: "08:45-09:45", course: "BEC", faculty: "Suneetha K", room: "Lab 114/102" },
            { day: "Tuesday", time: "09:45-10:45", course: "BEC", faculty: "Suneetha K", room: "Lab 114/102" },
            { day: "Tuesday", time: "09:45-10:45", course: "CA4", faculty: "Dileep", room: "Lab 103" },
            { day: "Tuesday", time: "11:00-12:00", course: "CA2", faculty: "Vandana J", room: "Lab 103" },
            { day: "Tuesday", time: "11:00-12:00", course: "DSA1", faculty: "Praveen K", room: "G09" },
            { day: "Tuesday", time: "11:00-12:00", course: "DSA3", faculty: "Aakash", room: "G08" },
            { day: "Tuesday", time: "12:00-13:00", course: "CA2", faculty: "Vandana J", room: "Lab 103" },
            { day: "Tuesday", time: "12:00-13:00", course: "SS1", faculty: "Pankaj V", room: "G09" },
            { day: "Tuesday", time: "12:00-13:00", course: "SS3", faculty: "Sujit S", room: "G07" },
            { day: "Tuesday", time: "14:15-15:15", course: "PS2", faculty: "K K B", room: "G09" },
            { day: "Tuesday", time: "14:15-15:15", course: "DSA3", faculty: "Aakash", room: "Lab 103" },
            { day: "Tuesday", time: "14:15-15:15", course: "OPC1", faculty: "Karthik S", room: "G08" },
            { day: "Tuesday", time: "15:15-16:15", course: "DSA2", faculty: "Suman Kumar", room: "G08" },
            { day: "Tuesday", time: "15:15-16:15", course: "DSA3", faculty: "Aakash", room: "Lab 103" },
            { day: "Tuesday", time: "15:15-16:15", course: "PS1", faculty: "Bhuvan T", room: "G09" },
            { day: "Tuesday", time: "16:30-17:30", course: "SS2", faculty: "Satrajit", room: "G09" },
            { day: "Tuesday", time: "16:30-17:30", course: "SS4", faculty: "Rakesh T", room: "G08" },
            { day: "Tuesday", time: "16:30-17:30", course: "CA1", faculty: "Monalisa G", room: "G07" },
            // Wednesday
            { day: "Wednesday", time: "08:45-09:45", course: "DSA1", faculty: "Praveen K", room: "Lab 103" },
            { day: "Wednesday", time: "08:45-09:45", course: "PS2", faculty: "K K B", room: "G09" },
            { day: "Wednesday", time: "08:45-09:45", course: "PS5", faculty: "Ram K", room: "G08" },
            { day: "Wednesday", time: "08:45-09:45", course: "CA3", faculty: "Prashant K", room: "G07" },
            { day: "Wednesday", time: "09:45-10:45", course: "SS2", faculty: "Satrajit", room: "G08" },
            { day: "Wednesday", time: "09:45-10:45", course: "DSA1", faculty: "Praveen K", room: "Lab 103" },
            { day: "Wednesday", time: "11:00-12:00", course: "CA2", faculty: "Vandana J", room: "G08" },
            { day: "Wednesday", time: "11:00-12:00", course: "CA1", faculty: "Monalisa G", room: "G07" },
            { day: "Wednesday", time: "11:00-12:00", course: "DSA4", faculty: "K V S R", room: "Lab 103" },
            { day: "Wednesday", time: "12:00-13:00", course: "DSA4", faculty: "K V S R", room: "Lab 103" },
            { day: "Wednesday", time: "12:00-13:00", course: "PS4", faculty: "Gautam P", room: "G09" },
            { day: "Wednesday", time: "12:00-13:00", course: "PS3", faculty: "Santhosh C", room: "G08" },
            { day: "Wednesday", time: "14:15-15:15", course: "CA3", faculty: "Prashant K", room: "Lab 103" },
            { day: "Wednesday", time: "14:15-15:15", course: "OPC4", faculty: "Kishore K", room: "G08" },
            { day: "Wednesday", time: "14:15-15:15", course: "SS1", faculty: "Pankaj V", room: "G09" },
            { day: "Wednesday", time: "15:15-16:15", course: "DSA2", faculty: "Suman Kumar", room: "G08" },
            { day: "Wednesday", time: "15:15-16:15", course: "CA3", faculty: "Prashant K", room: "Lab 103" },
            { day: "Wednesday", time: "15:15-16:15", course: "PS1", faculty: "Bhuvan T", room: "G09" },
            { day: "Wednesday", time: "16:30-17:30", course: "Faculty meeting", faculty: "-", room: "-" },
            // Thursday
            { day: "Thursday", time: "08:45-09:45", course: "PS4", faculty: "Gautam P", room: "G09" },
            { day: "Thursday", time: "08:45-09:45", course: "PS2", faculty: "K K B", room: "G08" },
            { day: "Thursday", time: "08:45-09:45", course: "CA3", faculty: "Prashant K", room: "G07" },
            { day: "Thursday", time: "09:45-10:45", course: "DSA4", faculty: "K V S R", room: "G09" },
            { day: "Thursday", time: "09:45-10:45", course: "DSA1", faculty: "Praveen K", room: "G08" },
            { day: "Thursday", time: "09:45-10:45", course: "SS3", faculty: "Sujit S", room: "G07" },
            { day: "Thursday", time: "09:45-10:45", course: "OPC2", faculty: "Anurag S", room: "G06" },
            { day: "Thursday", time: "11:00-12:00", course: "CA1", faculty: "Monalisa G", room: "Lab 103" },
            { day: "Thursday", time: "11:00-12:00", course: "CA2", faculty: "Vandana J", room: "G09" },
            { day: "Thursday", time: "11:00-12:00", course: "CA4", faculty: "Dileep", room: "G08" },
            { day: "Thursday", time: "12:00-13:00", course: "CA1", faculty: "Monalisa G", room: "Lab 103" },
            { day: "Thursday", time: "12:00-13:00", course: "PS3", faculty: "Santhosh C", room: "G09" },
            { day: "Thursday", time: "12:00-13:00", course: "PS4", faculty: "Gautam P", room: "G08" },
            { day: "Thursday", time: "12:00-13:00", course: "SS4", faculty: "Rakesh T", room: "G05" },
            { day: "Thursday", time: "14:15-15:15", course: "BEC", faculty: "Suneetha K", room: "G09" },
            { day: "Thursday", time: "14:15-15:15", course: "SS1", faculty: "Pankaj V", room: "Lab 103" },
            { day: "Thursday", time: "15:15-16:15", course: "SS1", faculty: "Pankaj V", room: "Lab 103" },
            { day: "Thursday", time: "15:15-16:15", course: "DSA3", faculty: "Aakash", room: "G08" },
            { day: "Thursday", time: "15:15-16:15", course: "PS5", faculty: "Ram K", room: "G09" },
            { day: "Thursday", time: "16:30-17:30", course: "AIV2", faculty: "Md. Aquib", room: "G08" },
            { day: "Thursday", time: "17:30-18:30", course: "AIV2", faculty: "Md. Aquib", room: "G08" },
            // Friday
            { day: "Friday", time: "08:45-09:45", course: "SS3", faculty: "Sujit S", room: "G09" },
            { day: "Friday", time: "08:45-09:45", course: "SS2", faculty: "Satrajit", room: "G08" },
            { day: "Friday", time: "08:45-09:45", course: "PS5", faculty: "Ram K", room: "G07" },
            { day: "Friday", time: "09:45-10:45", course: "DSA4", faculty: "K V S R", room: "G09" },
            { day: "Friday", time: "09:45-10:45", course: "CA4", faculty: "Dileep", room: "G08" },
            { day: "Friday", time: "11:00-12:00", course: "PS3", faculty: "Santhosh C", room: "G09" },
            { day: "Friday", time: "11:00-12:00", course: "PS4", faculty: "Gautam P", room: "G08" },
            { day: "Friday", time: "11:00-12:00", course: "PS1", faculty: "Bhuvan T", room: "G07" },
            { day: "Friday", time: "12:00-13:00", course: "OPC3", faculty: "Srinivas B", room: "G09" },
            { day: "Friday", time: "12:00-13:00", course: "OPC2", faculty: "Anurag S", room: "B03" },
            { day: "Friday", time: "12:00-13:00", course: "BEC", faculty: "Suneetha K", room: "G08" },
            { day: "Friday", time: "14:15-15:15", course: "DSA3", faculty: "Aakash", room: "G09" },
            { day: "Friday", time: "14:15-15:15", course: "DSA2", faculty: "Suman Kumar", room: "G08" },
            { day: "Friday", time: "14:15-15:15", course: "SS4", faculty: "Rakesh T", room: "Lab 103" },
            { day: "Friday", time: "15:15-16:15", course: "SS4", faculty: "Rakesh T", room: "Lab 103" },
            { day: "Friday", time: "15:15-16:15", course: "OPC1", faculty: "Karthik S", room: "G09" },
            { day: "Friday", time: "16:30-17:30", course: "AIV1", faculty: "Mounika J", room: "G09" },
            { day: "Friday", time: "17:30-18:30", course: "AIV1", faculty: "Mounika J", room: "G09" },
            // Saturday
            { day: "Saturday", time: "08:45-10:45", course: "EDL1", faculty: "Srinath", room: "G09" },
            { day: "Saturday", time: "11:00-13:00", course: "EDL2", faculty: "Soumya", room: "G09" },
        ]
    }
};
