import { PlaceHolderImages } from "./placeholder-images";

export const dummySchedule = [
    { time: "09:00 - 10:00", subject: "Data Structures", venue: "C-201" },
    { time: "10:00 - 11:00", subject: "Algorithms", venue: "C-202" },
    { time: "11:15 - 12:15", subject: "Database Systems", venue: "Lab 3" },
    { time: "14:00 - 15:00", subject: "Operating Systems", venue: "C-105" },
];

export const dummyAnnouncements = [
    {
        title: "HackOverflow 2024 Registrations Open",
        category: "Hackathons",
        date: "July 20, 2024",
        image: PlaceHolderImages.find(img => img.id === 'announcement-1')!
    },
    {
        title: "Guest Lecture on Quantum Computing",
        category: "Events",
        date: "July 22, 2024",
        image: PlaceHolderImages.find(img => img.id === 'announcement-2')!
    },
    {
        title: "Robotics Club Recruitment Drive",
        category: "Clubs",
        date: "July 25, 2024",
        image: PlaceHolderImages.find(img => img.id === 'announcement-3')!
    },
];

export const dummyCourses = [
  { id: 'PS', name: 'Probability and Statistics', abbr: 'PS' },
  { id: 'DSA', name: 'Data Structures and Algorithms', abbr: 'DSA' },
  { id: 'SS', name: 'Signals and Systems', abbr: 'SS' },
  { id: 'CA', name: 'Computer Architecture', abbr: 'CA' },
  { id: 'BEC', name: 'Basic Electronics and Circuit', abbr: 'BEC' },
  { id: 'OPC', name: 'Operational Communication', abbr: 'OPC' },
  { id: 'EDL', name: 'Ethics in Everyday Life', abbr: 'EDL' },
  { id: 'AIV', name: 'AI and Visual Culture', abbr: 'AIV' },
  { id: 'CCN', name: 'Computer and Communication Networks', abbr: 'CCN' },
  { id: 'FSD', name: 'FSD1 – Fundamentals of FSD', abbr: 'FSD' },
  { id: 'AI', name: 'Artificial Intelligence', abbr: 'AI' },
  { id: 'ToC', name: 'Theory of Computation', abbr: 'ToC' },
  { id: 'AC', name: 'Analog Circuits', abbr: 'AC' },
  { id: 'EMTL', name: 'Electromagnetics and Transmission Lines', abbr: 'EMTL' },
  { id: 'FComm', name: 'Fundamentals of Communication', abbr: 'FComm' },
  { id: 'AIKR', name: 'Artificial Intelligence & Knowledge Representation', abbr: 'AIKR' },
  { id: 'DL', name: 'Deep Learning', abbr: 'DL' },
  { id: 'IDA', name: 'Introduction to Data Analysis', abbr: 'IDA' },
  { id: 'ACS', name: 'Advanced Communication Skills', abbr: 'ACS' },
  { id: 'LR', name: 'Logical and Reasoning', abbr: 'LR' },
  { id: 'FFSD', name: 'FSD1 - Fundamentals of FSD', abbr: 'FFSD' },
  { id: 'ADA', name: 'Advanced Data Analytics', abbr: 'ADA' },
  { id: 'RL', name: 'Reinforcement Learning', abbr: 'RL' },
  { id: 'CDP', name: 'Compressed Domain Processing', abbr: 'CDP' },
  { id: 'DIP', name: 'Digital Image Processing', abbr: 'DIP' },
  { id: 'MOT', name: 'Mathematical Optimization Techniques', abbr: 'MOT' },
  { id: 'FDA', name: 'Financial Data Analysis', abbr: 'FDA' },
  { id: 'IDHV', name: 'Introduction Data Handling & Visualization', abbr: 'IDHV' },
  { id: 'DSY', name: 'Data Security', abbr: 'DSY' },
  { id: 'IS', name: 'Internet Security', abbr: 'IS' },
  { id: 'BCI', name: 'Brain Computer Interaction', abbr: 'BCI' },
  { id: 'GEOTA', name: 'Geospatial Technologies and Applications', abbr: 'GEOTA' },
  { id: 'MML', name: 'Mathematics for Machine Learning', abbr: 'MML' },
  { id: 'SPEECH', name: 'Speech Processing', abbr: 'SPEECH' },
  { id: 'IOT', name: 'Internet of Things', abbr: 'IOT' },
  { id: 'IAS', name: 'Intelligent Autonomous Systems', abbr: 'IAS' },
  { id: 'MSA', name: 'Micro Sensors and Actuators', abbr: 'MSA' },
  { id: 'ONE', name: 'Opto and Nano Electronics', abbr: 'ONE' },
  { id: 'HDL', name: 'Verilog Hardware Description Language', abbr: 'HDL' },
  { id: 'PE', name: 'Power Electronics', abbr: 'PE' },
  { id: 'AVLSI', name: 'Advanced VLSI', abbr: 'AVLSI' },
  { id: 'SOC', name: 'System on Chip', abbr: 'SOC' },
  { id: 'CB', name: 'Computational Biology', abbr: 'CB' },
  { id: 'UBC', name: 'Ubiquitous Computing', abbr: 'UBC' },
  { id: 'WN', name: 'Wireless Networks', abbr: 'WN' }
];


export const dummyFaculty = [
  // UG-1 Faculty
  { "id": "faculty-ps-1", "name": "Dr. Mansoori", "email": "ps1@iiits.in", "courseName": "Probability and Statistics", "courseAbbr": "PS", "branch": "CSE,ECE,AIDS", "section": "1", "ugYear": ["1"] },
  { "id": "faculty-ps-2", "name": "Dr. Jahnabi Chakravarty", "email": "ps2@iiits.in", "courseName": "Probability and Statistics", "courseAbbr": "PS", "branch": "CSE,ECE,AIDS", "section": "2", "ugYear": ["1"] },
  { "id": "faculty-ps-3", "name": "Dr. Jahnabi Chakravarty", "email": "ps3@iiits.in", "courseName": "Probability and Statistics", "courseAbbr": "PS", "branch": "CSE,ECE,AIDS", "section": "3", "ugYear": ["1"] },
  { "id": "faculty-ps-4", "name": "Dr. Narendra Singh Yadav", "email": "ps4@iiits.in", "courseName": "Probability and Statistics", "courseAbbr": "PS", "branch": "CSE,ECE,AIDS", "section": "4", "ugYear": ["1"] },
  { "id": "faculty-ps-5", "name": "Dr. Narendra Singh Yadav", "email": "ps5@iiits.in", "courseName": "Probability and Statistics", "courseAbbr": "PS", "branch": "CSE,ECE,AIDS", "section": "5", "ugYear": ["1"] },
  { "id": "faculty-dsa-1", "name": "Dr. A U G Sankaranrao", "email": "dsa1@iiits.in", "courseName": "Data Structures and Algorithms", "courseAbbr": "DSA", "branch": "CSE,ECE,AIDS", "section": "1", "ugYear": ["1"] },
  { "id": "faculty-dsa-2", "name": "Dr. A U G Sankaranrao", "email": "dsa2@iiits.in", "courseName": "Data Structures and Algorithms", "courseAbbr": "DSA", "branch": "CSE,ECE,AIDS", "section": "2", "ugYear": ["1"] },
  { "id": "faculty-dsa-3", "name": "Dr. Viswanath Pulabagari", "email": "dsa3@iiits.in", "courseName": "Data Structures and Algorithms", "courseAbbr": "DSA", "branch": "CSE,ECE,AIDS", "section": "3", "ugYear": ["1"] },
  { "id": "faculty-dsa-4", "name": "Dr. Viswanath Pulabagari", "email": "dsa4@iiits.in", "courseName": "Data Structures and Algorithms", "courseAbbr": "DSA", "branch": "CSE,ECE,AIDS", "section": "4", "ugYear": ["1"] },
  { "id": "faculty-ss-1", "name": "Dr. Divyambham", "email": "ss1@iiits.in", "courseName": "Signals and Systems", "courseAbbr": "SS", "branch": "CSE,AIDS", "section": "1", "ugYear": ["1"] },
  { "id": "faculty-ss-2", "name": "Dr. Anish Chand Turlapaty", "email": "ss2@iiits.in", "courseName": "Signals and Systems", "courseAbbr": "SS", "branch": "CSE,AIDS", "section": "2", "ugYear": ["1"] },
  { "id": "faculty-ss-3", "name": "Dr. Achintya Sarkar", "email": "ss3@iiits.in", "courseName": "Signals and Systems", "courseAbbr": "SS", "branch": "CSE,AIDS", "section": "3", "ugYear": ["1"] },
  { "id": "faculty-ss-4", "name": "Dr. Achintya Sarkar", "email": "ss4@iiits.in", "courseName": "Signals and Systems", "courseAbbr": "SS", "branch": "CSE,AIDS", "section": "4", "ugYear": ["1"] },
  { "id": "faculty-ca-1", "name": "Dr. Santhosh A", "email": "ca1@iiits.in", "courseName": "Computer Architecture", "courseAbbr": "CA", "branch": "CSE,AIDS", "section": "1", "ugYear": ["1"] },
  { "id": "faculty-ca-2", "name": "Dr. Bheemappa Halavar", "email": "ca2@iiits.in", "courseName": "Computer Architecture", "courseAbbr": "CA", "branch": "CSE,AIDS", "section": "2", "ugYear": ["1"] },
  { "id": "faculty-ca-3", "name": "Dr. Bheemappa Halavar", "email": "ca3@iiits.in", "courseName": "Computer Architecture", "courseAbbr": "CA", "branch": "CSE,AIDS", "section": "3", "ugYear": ["1"] },
  { "id": "faculty-ca-4", "name": "Dr. Kartick Sutradhar", "email": "ca4@iiits.in", "courseName": "Computer Architecture", "courseAbbr": "CA", "branch": "CSE,AIDS", "section": "4", "ugYear": ["1"] },
  { "id": "faculty-bec-1", "name": "Dr. Raja Vara Prasad Y / Mrs. Srivalli", "email": "bec@iiits.in", "courseName": "Basic Electronics and Circuit", "courseAbbr": "BEC", "branch": "ECE", "section": "Common", "ugYear": ["1"] },
  { "id": "faculty-opc-1", "name": "Dr. Vinay Kumar", "email": "opc1@iiits.in", "courseName": "Operational Communication", "courseAbbr": "OPC", "branch": "CSE,ECE,AIDS", "section": "1", "ugYear": ["1"] },
  { "id": "faculty-opc-2", "name": "Dr. Vinay Kumar", "email": "opc2@iiits.in", "courseName": "Operational Communication", "courseAbbr": "OPC", "branch": "CSE,ECE,AIDS", "section": "2", "ugYear": ["1"] },
  { "id": "faculty-opc-3", "name": "Dr. Krishna Swamy", "email": "opc3@iiits.in", "courseName": "Operational Communication", "courseAbbr": "OPC", "branch": "CSE,ECE,AIDS", "section": "3", "ugYear": ["1"] },
  { "id": "faculty-opc-4", "name": "Dr. Krishna Swamy", "email": "opc4@iiits.in", "courseName": "Operational Communication", "courseAbbr": "OPC", "branch": "CSE,ECE,AIDS", "section": "4", "ugYear": ["1"] },
  { "id": "faculty-edl-1", "name": "Dr. Rosemaria Regy Mathew", "email": "edl1@iiits.in", "courseName": "Ethics in Everyday Life", "courseAbbr": "EDL", "branch": "CSE,ECE,AIDS", "section": "1", "ugYear": ["1"] },
  { "id": "faculty-edl-2", "name": "Dr. Rosemaria Regy Mathew", "email": "edl2@iiits.in", "courseName": "Ethics in Everyday Life", "courseAbbr": "EDL", "branch": "CSE,ECE,AIDS", "section": "2", "ugYear": ["1"] },
  { "id": "faculty-aiv-1", "name": "Dr. Rosemaria Regy Mathew", "email": "aiv1@iiits.in", "courseName": "AI and Visual Culture", "courseAbbr": "AIV", "branch": "CSE,ECE,AIDS", "section": "1", "ugYear": ["1"] },
  { "id": "faculty-aiv-2", "name": "Dr. Rosemaria Regy Mathew", "email": "aiv2@iiits.in", "courseName": "AI and Visual Culture", "courseAbbr": "AIV", "branch": "CSE,ECE,AIDS", "section": "2", "ugYear": ["1"] },
  // UG-2 Faculty
  { "id": "faculty-ccn-1", "name": "Dr. Hemant Kumar", "email": "cn1@iiits.in", "courseName": "Computer and Communication Networks", "courseAbbr": "CCN", "branch": "CSE,ECE,AIDS", "section": "1", "ugYear": ["2"] },
  { "id": "faculty-ccn-2", "name": "Dr. U Somalatha", "email": "cn2@iiits.in", "courseName": "Computer and Communication Networks", "courseAbbr": "CCN", "branch": "CSE,ECE,AIDS", "section": "2", "ugYear": ["2"] },
  { "id": "faculty-ccn-3", "name": "Dr. Raja Vara Prasad Y", "email": "cn3@iiits.in", "courseName": "Computer and Communication Networks", "courseAbbr": "CCN", "branch": "CSE,ECE,AIDS", "section": "3", "ugYear": ["2"] },
  { "id": "faculty-ccn-4", "name": "Dr. Rajeev Kumar", "email": "cn4@iiits.in", "courseName": "Computer and Communication Networks", "courseAbbr": "CCN", "branch": "CSE,ECE,AIDS", "section": "4", "ugYear": ["2"] },
  { "id": "faculty-ffsd-1", "name": "Dr. D. Mallikarjuna Reddy", "email": "ffsd1@iiits.in", "courseName": "FSD1 - Fundamentals of FSD", "courseAbbr": "FFSD", "branch": "CSE", "section": "1", "ugYear": ["2"] },
  { "id": "faculty-ffsd-2", "name": "Dr. Anushree Bablani", "email": "ffsd2@iiits.in", "courseName": "FSD1 - Fundamentals of FSD", "courseAbbr": "FFSD", "branch": "CSE", "section": "2", "ugYear": ["2"] },
  { "id": "faculty-ffsd-3", "name": "Dr. Mrinmoy Ghosh", "email": "ffsd3@iiits.in", "courseName": "FSD1 - Fundamentals of FSD", "courseAbbr": "FFSD", "branch": "CSE", "section": "3", "ugYear": ["2"] },
  { "id": "faculty-ai-1", "name": "Dr. Priyambada Subudhi", "email": "ai1@iiits.in", "courseName": "Artificial Intelligence", "courseAbbr": "AI", "branch": "CSE", "section": "1", "ugYear": ["2"] },
  { "id": "faculty-ai-2", "name": "Dr. Piyush Joshi", "email": "ai2@iiits.in", "courseName": "Artificial Intelligence", "courseAbbr": "AI", "branch": "CSE", "section": "2", "ugYear": ["2"] },
  { "id": "faculty-ai-3", "name": "Dr. Bulla Rajesh", "email": "ai3@iiits.in", "courseName": "Artificial Intelligence", "courseAbbr": "AI", "branch": "CSE", "section": "3", "ugYear": ["2"] },
  { "id": "faculty-toc-1", "name": "Dr. D Mallikarjuna Reddy", "email": "toc1@iiits.in", "courseName": "Theory of Computation", "courseAbbr": "ToC", "branch": "CSE", "section": "1", "ugYear": ["2"] },
  { "id": "faculty-toc-2", "name": "Dr. Kartick Sutradhar", "email": "toc2@iiits.in", "courseName": "Theory of Computation", "courseAbbr": "ToC", "branch": "CSE", "section": "2", "ugYear": ["2"] },
  { "id": "faculty-toc-3", "name": "Dr. B N Pavan Kumar", "email": "toc3@iiits.in", "courseName": "Theory of Computation", "courseAbbr": "ToC", "branch": "CSE", "section": "3", "ugYear": ["2"] },
  { "id": "faculty-ac-1", "name": "Dr. Paul Brainerd", "email": "ac@iiits.in", "courseName": "Analog Circuits", "courseAbbr": "AC", "branch": "ECE", "section": "Common", "ugYear": ["2"] },
  { "id": "faculty-emtl-1", "name": "Dr. Lokendra Chauhan", "email": "emtl@iiits.in", "courseName": "Electromagnetics and Transmission Lines", "courseAbbr": "EMTL", "branch": "ECE", "section": "Common", "ugYear": ["2"] },
  { "id": "faculty-fcomm-1", "name": "Dr. Rajeev Kumar", "email": "fcomm@iiits.in", "courseName": "Fundamentals of Communication", "courseAbbr": "FComm", "branch": "ECE", "section": "Common", "ugYear": ["2"] },
  { "id": "faculty-aikr-1", "name": "Dr. Anushree Bablani", "email": "aikr@iiits.in", "courseName": "Artificial Intelligence & Knowledge Representation", "courseAbbr": "AIKR", "branch": "AIDS", "section": "Common", "ugYear": ["2"] },
  { "id": "faculty-dl-2-1", "name": "Dr. Pavan Kumar Perepu", "email": "dl2-1@iiits.in", "courseName": "Deep Learning", "courseAbbr": "DL", "branch": "AIDS", "section": "Common", "ugYear": ["2"] },
  { "id": "faculty-ida-1", "name": "Dr. Pavan Kumar Perepu", "email": "ida@iiits.in", "courseName": "Introduction to Data Analysis", "courseAbbr": "IDA", "branch": "AIDS", "section": "Common", "ugYear": ["2"] },
  { "id": "faculty-acs-1", "name": "Dr. Vinay Kumar", "email": "acs1@iiits.in", "courseName": "Advanced Communication Skills", "courseAbbr": "ACS", "branch": "CSE,ECE,AIDS", "section": "1", "ugYear": ["2"] },
  { "id": "faculty-acs-2", "name": "Dr. Vinay Kumar", "email": "acs2@iiits.in", "courseName": "Advanced Communication Skills", "courseAbbr": "ACS", "branch": "CSE,ECE,AIDS", "section": "2", "ugYear": ["2"] },
  { "id": "faculty-acs-3", "name": "Dr. Krishna Swamy", "email": "acs3@iiits.in", "courseName": "Advanced Communication Skills", "courseAbbr": "ACS", "branch": "CSE,ECE,AIDS", "section": "3", "ugYear": ["2"] },
  { "id": "faculty-acs-4", "name": "Dr. Krishna Swamy", "email": "acs4@iiits.in", "courseName": "Advanced Communication Skills", "courseAbbr": "ACS", "branch": "CSE,ECE,AIDS", "section": "4", "ugYear": ["2"] },
  { "id": "faculty-lr-1", "name": "Mrs. Shabhana Imran", "email": "lr1@iiits.in", "courseName": "Logical and Reasoning", "courseAbbr": "LR", "branch": "CSE,ECE,AIDS", "section": "1", "ugYear": ["2"] },
  { "id": "faculty-lr-2", "name": "Mrs. Shabhana Imran", "email": "lr2@iiits.in", "courseName": "Logical and Reasoning", "courseAbbr": "LR", "branch": "CSE,ECE,AIDS", "section": "2", "ugYear": ["2"] },
  { "id": "faculty-lr-3", "name": "Mrs. Shabhana Imran", "email": "lr3@iiits.in", "courseName": "Logical and Reasoning", "courseAbbr": "LR", "branch": "CSE,ECE,AIDS", "section": "3", "ugYear": ["2"] },
  { "id": "faculty-lr-4", "name": "Mrs. Shabhana Imran", "email": "lr4@iiits.in", "courseName": "Logical and Reasoning", "courseAbbr": "LR", "branch": "CSE,ECE,AIDS", "section": "4", "ugYear": ["2"] },
  // UG-3 Faculty
  { "id": "faculty-ada-1", "name": "Dr. Mainak Thakur", "email": "ada@iiits.in", "courseName": "Advanced Data Analytics", "courseAbbr": "ADA", "branch": "CSE,AIDS", "section": "Common", "ugYear": ["3"] },
  { "id": "faculty-dl-3-1", "name": "Dr. Shaik Mohammad Rafi", "email": "dl@iiits.in", "courseName": "Deep Learning", "courseAbbr": "DL", "branch": "CSE", "section": "Common", "ugYear": ["3"] },
  { "id": "faculty-rl-1", "name": "Dr. Arun PV", "email": "rl@iiits.in", "courseName": "Reinforcement Learning", "courseAbbr": "RL", "branch": "CSE,AIDS", "section": "Common", "ugYear": ["3"] },
  { "id": "faculty-mot-1", "name": "Dr. Mohd Shanawaz Mansoori", "email": "mot@iiits.in", "courseName": "Mathematical Optimization Techniques", "courseAbbr": "MOT", "branch": "SE,DS,PEAI", "section": "Common", "ugYear": ["3"] },
  { "id": "faculty-fda-1", "name": "Dr. Shiv Mohan", "email": "fda@iiits.in", "courseName": "Financial Data Analysis", "courseAbbr": "FDA", "branch": "SE,DS,PEAI", "section": "Common", "ugYear": ["3"] },
  { "id": "faculty-idhv-1", "name": "Dr. Mainak Thakur / Dr. Rajendra Prasath", "email": "idhv@iiits.in", "courseName": "Introduction Data Handling & Visualization", "courseAbbr": "IDHV", "branch": "SE,DS,PEAI", "section": "Common", "ugYear": ["3"] },
  { "id": "faculty-ada-2", "name": "Dr. Mainak Thakur", "email": "ada2@iiits.in", "courseName": "Advanced Data Analytics", "courseAbbr": "ADA", "branch": "SE,AIML,PE,AIDS", "section": "Common", "ugYear": ["3"] },
  { "id": "faculty-dsy-1", "name": "Dr. U Somalatha", "email": "dsy@iiits.in", "courseName": "Data Security", "courseAbbr": "DSY", "branch": "CSE,AI,DS,Cybersec", "section": "Common", "ugYear": ["3"] },
  { "id": "faculty-is-1", "name": "Dr. Kamalakanta Sethi", "email": "is1@iiits.in", "courseName": "Internet Security", "courseAbbr": "IS", "branch": "PE,CSE,Cybersec", "section": "1", "ugYear": ["3"] },
  { "id": "faculty-is-2", "name": "Dr. Kamalakanta Sethi", "email": "is2@iiits.in", "courseName": "Internet Security", "courseAbbr": "IS", "branch": "PE,CSE,Cybersec", "section": "2", "ugYear": ["3"] },
  { "id": "faculty-bci-1", "name": "Dr. Kamalakanta Sethi", "email": "bci@iiits.in", "courseName": "Brain Computer Interaction", "courseAbbr": "BCI", "branch": "PE,CSE", "section": "Common", "ugYear": ["3"] },
  { "id": "faculty-geota-1", "name": "Dr. Arun PV", "email": "geota@iiits.in", "courseName": "Geospatial Technologies and Applications", "courseAbbr": "GEOTA", "branch": "CSE,ECE,AIDS", "section": "Common", "ugYear": ["3"] },
  { "id": "faculty-mml-1", "name": "Dr. Selvi R", "email": "mml@iiits.in", "courseName": "Mathematics for Machine Learning", "courseAbbr": "MML", "branch": "CSE,ECE,AIDS", "section": "Common", "ugYear": ["3"] },
  { "id": "faculty-speech-1", "name": "Dr. Shaik Mohammad Rafi", "email": "spp@iiits.in", "courseName": "Speech Processing", "courseAbbr": "SPEECH", "branch": "CSE,ECE,AIDS", "section": "Common", "ugYear": ["3"] },
  { "id": "faculty-iot-1", "name": "Dr. Lokendra Chouhan", "email": "iot@iiits.in", "courseName": "Internet of Things", "courseAbbr": "IOT", "branch": "ECE", "section": "Common", "ugYear": ["3"] },
  { "id": "faculty-ias-1", "name": "Dr. Sakthi Swaroop", "email": "ias@iiits.in", "courseName": "Intelligent Autonomous Systems", "courseAbbr": "IAS", "branch": "ECE", "section": "Common", "ugYear": ["3"] },
  { "id": "faculty-msa-1", "name": "Dr. Priyanka Dwivedi", "email": "msa@iiits.in", "courseName": "Micro Sensors and Actuators", "courseAbbr": "MSA", "branch": "ECE", "section": "Common", "ugYear": ["3"] },
  { "id": "faculty-one-1", "name": "Dr. Visaprasad Kotamaraju", "email": "one@iiits.in", "courseName": "Opto and Nano Electronics", "courseAbbr": "ONE", "branch": "ECE", "section": "Common", "ugYear": ["3"] },
  { "id": "faculty-hdl-1", "name": "Dr. V. Ramesh Kumar", "email": "hdl@iiits.in", "courseName": "Verilog Hardware Description Language", "courseAbbr": "HDL", "branch": "ECE", "section": "Common", "ugYear": ["3"] },
  { "id": "faculty-pe-1", "name": "Dr. Paul Brainerd", "email": "pe@iiits.in", "courseName": "Power Electronics", "courseAbbr": "PE", "branch": "ECE", "section": "Common", "ugYear": ["3"] },
  // UG-4 Faculty
  { "id": "faculty-cdp-1", "name": "Dr. Bulla Rajesh", "email": "cdp@iiits.in", "courseName": "Compressed Domain Processing", "courseAbbr": "CDP", "branch": "CSE", "section": "Common", "ugYear": ["4"] },
  { "id": "faculty-dip-1", "name": "Dr. Mrinmoy Ghorai", "email": "dip@iiits.in", "courseName": "Digital Image Processing", "courseAbbr": "DIP", "branch": "CSE,ECE", "section": "Common", "ugYear": ["4"] },
  { "id": "faculty-avlsi-1", "name": "Dr. Priyanka Dwivedi", "email": "avlsi@iiits.in", "courseName": "Advanced VLSI", "courseAbbr": "AVLSI", "branch": "CSE", "section": "Common", "ugYear": ["4"] },
  { "id": "faculty-soc-1", "name": "Dr. V. Ramesh Kumar", "email": "soc@iiits.in", "courseName": "System on Chip", "courseAbbr": "SOC", "branch": "CSE", "section": "Common", "ugYear": ["4"] },
  { "id": "faculty-cb-1", "name": "Dr. Santhosh A", "email": "cb@iiits.in", "courseName": "Computational Biology", "courseAbbr": "CB", "branch": "CSE", "section": "Common", "ugYear": ["4"] },
  { "id": "faculty-ubc-1", "name": "Dr. Hemant Kumar", "email": "ubc@iiits.in", "courseName": "Ubiquitous Computing", "courseAbbr": "UBC", "branch": "CSE", "section": "Common", "ugYear": ["4"] },
  { "id": "faculty-wn-1", "name": "Dr. Hrishikesh Venkataraman", "email": "wn@iiits.in", "courseName": "Wireless Networks", "courseAbbr": "WN", "branch": "CSE,ECE", "section": "Common", "ugYear": ["4"] }
];

export const dummyTimetable = {
    "UG1": {
        "Common": [
            // Monday
            { day: "Monday", time: "08:45-09:45", course: "DSA1", faculty: "Praveen K", room: "G09" },
            { day: "Monday", time: "08:45-09:45", course: "DSA4", faculty: "K V S R", room: "G08" },
            { day: "Monday", time: "08:45-09:45", course: "SS2", faculty: "Satrajit", room: "Lab 103" },
            { day: "Monday", time: "08:45-09:45", course: "OPC3", faculty: "Srinivas B", room: "G07" },
            { day: "Monday", time: "09:45-10:45", course: "SS2", faculty: "Satrajit", room: "Lab 103" },
            { day: "Monday", time: "09:45-10:45", course: "PS3", faculty: "Santhosh C", room: "G08" },
            { day: "Monday", time: "11:00-12:00", course: "CA2", faculty: "Vandana J", room: "G09" },
            { day: "Monday", time: "11:00-12:00", course: "PS1", faculty: "Bhuvan T", room: "G07" },
            { day: "Monday", time: "11:00-12:00", course: "SS3", faculty: "Sujit S", room: "Lab 103" },
            { day: "Monday", time: "12:00-13:00", course: "SS3", faculty: "Sujit S", room: "Lab 103" },
            { day: "Monday", time: "12:00-13:00", course: "PS2", faculty: "K K B", room: "G09" },
            { day: "Monday", time: "12:00-13:00", course: "CA1", faculty: "Monalisa G", room: "G08" },
            { day: "Monday", time: "12:00-13:00", course: "BEC", faculty: "Suneetha K", room: "G07" },
            { day: "Monday", time: "14:15-15:15", course: "SS1", faculty: "Pankaj V", room: "G08" },
            { day: "Monday", time: "14:15-15:15", course: "DSA2", faculty: "Suman Kumar", room: "Lab 103" },
            { day: "Monday", time: "14:15-15:15", course: "SS4", faculty: "Rakesh T", room: "G09" },
            { day: "Monday", time: "15:15-16:15", course: "DSA2", faculty: "Suman Kumar", room: "Lab 103" },
            { day: "Monday", time: "15:15-16:15", course: "OPC4", faculty: "Kishore K", room: "G08" },
            { day: "Monday", time: "16:30-17:30", course: "CA4", faculty: "Dileep", room: "G08" },
            { day: "Monday", time: "16:30-17:30", course: "PS5", faculty: "Ram K", room: "G09" },
            { day: "Monday", time: "16:30-17:30", course: "CA3", faculty: "Prashant K", room: "G07" },
            // Tuesday
            { day: "Tuesday", time: "08:45-09:45", course: "CA4", faculty: "Dileep", room: "Lab 103" },
            { day: "Tuesday", time: "08:45-09:45", course: "BEC", faculty: "Suneetha K", room: "Lab 114/102" },
            { day: "Tuesday", time: "09:45-10:45", course: "BEC", faculty: "Suneetha K", room: "Lab 114/102" },
            { day: "Tuesday", time: "09:45-10:45", course: "CA4", faculty: "Dileep", room: "Lab 103" },
            { day: "Tuesday", time: "11:00-12:00", course: "CA2", faculty: "Vandana J", room: "Lab 103" },
            { day: "Tuesday", time: "11:00-12:00", course: "DSA1", faculty: "Praveen K", room: "G09" },
            { day: "Tuesday", time: "11:00-12:00", course: "DSA3", faculty: "Aakash", room: "G08" },
            { day: "Tuesday", time: "12:00-13:00", course: "CA2", faculty: "Vandana J", room: "Lab 103" },
            { day: "Tuesday", time: "12:00-13:00", course: "SS1", faculty: "Pankaj V", room: "G09" },
            { day: "Tuesday", time: "12:00-13:00", course: "SS3", faculty: "Sujit S", room: "G07" },
            { day: "Tuesday", time: "14:15-15:15", course: "PS2", faculty: "K K B", room: "G09" },
            { day: "Tuesday", time: "14:15-15:15", course: "DSA3", faculty: "Aakash", room: "Lab 103" },
            { day: "Tuesday", time: "14:15-15:15", course: "OPC1", faculty: "Karthik S", room: "G08" },
            { day: "Tuesday", time: "15:15-16:15", course: "DSA2", faculty: "Suman Kumar", room: "G08" },
            { day: "Tuesday", time: "15:15-16:15", course: "DSA3", faculty: "Aakash", room: "Lab 103" },
            { day: "Tuesday", time: "15:15-16:15", course: "PS1", faculty: "Bhuvan T", room: "G09" },
            { day: "Tuesday", time: "16:30-17:30", course: "SS2", faculty: "Satrajit", room: "G09" },
            { day: "Tuesday", time: "16:30-17:30", course: "SS4", faculty: "Rakesh T", room: "G08" },
            { day: "Tuesday", time: "16:30-17:30", course: "CA1", faculty: "Monalisa G", room: "G07" },
            // Wednesday
            { day: "Wednesday", time: "08:45-09:45", course: "DSA1", faculty: "Praveen K", room: "Lab 103" },
            { day: "Wednesday", time: "08:45-09:45", course: "PS2", faculty: "K K B", room: "G09" },
            { day: "Wednesday", time: "08:45-09:45", course: "PS5", faculty: "Ram K", room: "G08" },
            { day: "Wednesday", time: "08:45-09:45", course: "CA3", faculty: "Prashant K", room: "G07" },
            { day: "Wednesday", time: "09:45-10:45", course: "SS2", faculty: "Satrajit", room: "G08" },
            { day: "Wednesday", time: "09:45-10:45", course: "DSA1", faculty: "Praveen K", room: "Lab 103" },
            { day: "Wednesday", time: "11:00-12:00", course: "CA2", faculty: "Vandana J", room: "G08" },
            { day: "Wednesday", time: "11:00-12:00", course: "CA1", faculty: "Monalisa G", room: "G07" },
            { day: "Wednesday", time: "11:00-12:00", course: "DSA4", faculty: "K V S R", room: "Lab 103" },
            { day: "Wednesday", time: "12:00-13:00", course: "DSA4", faculty: "K V S R", room: "Lab 103" },
            { day: "Wednesday", time: "12:00-13:00", course: "PS4", faculty: "Gautam P", room: "G09" },
            { day: "Wednesday", time: "12:00-13:00", course: "PS3", faculty: "Santhosh C", room: "G08" },
            { day: "Wednesday", time: "14:15-15:15", course: "CA3", faculty: "Prashant K", room: "Lab 103" },
            { day: "Wednesday", time: "14:15-15:15", course: "OPC4", faculty: "Kishore K", room: "G08" },
            { day: "Wednesday", time: "14:15-15:15", course: "SS1", faculty: "Pankaj V", room: "G09" },
            { day: "Wednesday", time: "15:15-16:15", course: "DSA2", faculty: "Suman Kumar", room: "G08" },
            { day: "Wednesday", time: "15:15-16:15", course: "CA3", faculty: "Prashant K", room: "Lab 103" },
            { day: "Wednesday", time: "15:15-16:15", course: "PS1", faculty: "Bhuvan T", room: "G09" },
            { day: "Wednesday", time: "16:30-17:30", course: "Faculty meeting", faculty: "-", room: "-" },
            // Thursday
            { day: "Thursday", time: "08:45-09:45", course: "PS4", faculty: "Gautam P", room: "G09" },
            { day: "Thursday", time: "08:45-09:45", course: "PS2", faculty: "K K B", room: "G08" },
            { day: "Thursday", time: "08:45-09:45", course: "CA3", faculty: "Prashant K", room: "G07" },
            { day: "Thursday", time: "09:45-10:45", course: "DSA4", faculty: "K V S R", room: "G09" },
            { day: "Thursday", time: "09:45-10:45", course: "DSA1", faculty: "Praveen K", room: "G08" },
            { day: "Thursday", time: "09:45-10:45", course: "SS3", faculty: "Sujit S", room: "G07" },
            { day: "Thursday", time: "09:45-10:45", course: "OPC2", faculty: "Anurag S", room: "G06" },
            { day: "Thursday", time: "11:00-12:00", course: "CA1", faculty: "Monalisa G", room: "Lab 103" },
            { day: "Thursday", time: "11:00-12:00", course: "CA2", faculty: "Vandana J", room: "G09" },
            { day: "Thursday", time: "11:00-12:00", course: "CA4", faculty: "Dileep", room: "G08" },
            { day: "Thursday", time: "12:00-13:00", course: "CA1", faculty: "Monalisa G", room: "Lab 103" },
            { day: "Thursday", time: "12:00-13:00", course: "PS3", faculty: "Santhosh C", room: "G09" },
            { day: "Thursday", time: "12:00-13:00", course: "PS4", faculty: "Gautam P", room: "G08" },
            { day: "Thursday", time: "12:00-13:00", course: "SS4", faculty: "Rakesh T", room: "G05" },
            { day: "Thursday", time: "14:15-15:15", course: "BEC", faculty: "Suneetha K", room: "G09" },
            { day: "Thursday", time: "14:15-15:15", course: "SS1", faculty: "Pankaj V", room: "Lab 103" },
            { day: "Thursday", time: "15:15-16:15", course: "SS1", faculty: "Pankaj V", room: "Lab 103" },
            { day: "Thursday", time: "15:15-16:15", course: "DSA3", faculty: "Aakash", room: "G08" },
            { day: "Thursday", time: "15:15-16:15", course: "PS5", faculty: "Ram K", room: "G09" },
            { day: "Thursday", time: "16:30-17:30", course: "AIV2", faculty: "Md. Aquib", room: "G08" },
            { day: "Thursday", time: "17:30-18:30", course: "AIV2", faculty: "Md. Aquib", room: "G08" },
            // Friday
            { day: "Friday", time: "08:45-09:45", course: "SS3", faculty: "Sujit S", room: "G09" },
            { day: "Friday", time: "08:45-09:45", course: "SS2", faculty: "Satrajit", room: "G08" },
            { day: "Friday", time: "08:45-09:45", course: "PS5", faculty: "Ram K", room: "G07" },
            { day: "Friday", time: "09:45-10:45", course: "DSA4", faculty: "K V S R", room: "G09" },
            { day: "Friday", time: "09:45-10:45", course: "CA4", faculty: "Dileep", room: "G08" },
            { day: "Friday", time: "11:00-12:00", course: "PS3", faculty: "Santhosh C", room: "G09" },
            { day: "Friday", time: "11:00-12:00", course: "PS4", faculty: "Gautam P", room: "G08" },
            { day: "Friday", time: "11:00-12:00", course: "PS1", faculty: "Bhuvan T", room: "G07" },
            { day: "Friday", time: "12:00-13:00", course: "OPC3", faculty: "Srinivas B", room: "G09" },
            { day: "Friday", time: "12:00-13:00", course: "OPC2", faculty: "Anurag S", room: "B03" },
            { day: "Friday", time: "12:00-13:00", course: "BEC", faculty: "Suneetha K", room: "G08" },
            { day: "Friday", time: "14:15-15:15", course: "DSA3", faculty: "Aakash", room: "G09" },
            { day: "Friday", time: "14:15-15:15", course: "DSA2", faculty: "Suman Kumar", room: "G08" },
            { day: "Friday", time: "14:15-15:15", course: "SS4", faculty: "Rakesh T", room: "Lab 103" },
            { day: "Friday", time: "15:15-16:15", course: "SS4", faculty: "Rakesh T", room: "Lab 103" },
            { day: "Friday", time: "15:15-16:15", course: "OPC1", faculty: "Karthik S", room: "G09" },
            { day: "Friday", time: "16:30-17:30", course: "AIV1", faculty: "Mounika J", room: "G09" },
            { day: "Friday", time: "17:30-18:30", course: "AIV1", faculty: "Mounika J", room: "G09" },
            // Saturday
            { day: "Saturday", time: "08:45-10:45", course: "EDL1", faculty: "Srinath", room: "G09" },
            { day: "Saturday", time: "11:00-13:00", course: "EDL2", faculty: "Soumya", room: "G09" },
        ]
    }
};



    

    